[workspace]
members = ["nnue-constants", "eidolon-lib", "eidolon-bin", "visualizer"]
exclude = ["torch-trainer", "sanity-check"]
resolver = "2"

[profile.release]
debug = true

[profile.release-lto]
inherits = "release"
lto = true
codegen-units = 1
panic = "abort"
strip = true
