[package]
name = "sanity-check"
version = "0.1.0"
edition = "2024"

[dependencies]
eidolon = { path = "../eidolon-lib" }
torch = { path = "../torch-trainer" }
nnue-constants = { path = "../nnue-constants" }
tch = "0.19"
